### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by nghiencuuthuoc** [ale94mleon/MolDrug#4] opened 2022-07-20 08:03 UTC
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [2], in <cell line: 2>()
      1 from rdkit import Chem
----> 2 from moldrug import utils, fitness
      3 from moldrug.data import receptors, ligands, boxes
      4 import tempfile, os, gzip, shutil, requests

File ~/anaconda3/envs/py38_rdkit/lib/python3.8/site-packages/moldrug/utils.py:101, in <module>
     98     else:
     99         return pdbqt_string
--> 101 def get_sim(ms:list[Chem.rdchem.Mol], ref_fps:list):
    102     """Get the molecules with higher similarity to each member of ref_fps.
    103 
    104     Parameters
   (...)
    114         A list of molecules with the higher similarity with their corresponded ref_fps value.
    115     """
    116     output = []

TypeError: 'type' object is not subscriptable

**Comment by ale94mleon** [comment] 2022-07-20 10:54
Hi, thanks for brings this up! The problem is the python version. I suppose that you are using python 3.8. The thing is that python 3.8 does not accept the Type Hints `list[Chem.rdchem.Mol]` that is used in the function `get_sim`.
The solution could be either update to python 3.9 or higher or even better create an isolated environment for MolDrug as is set on the [installations instructions](https://moldrug.readthedocs.io/en/latest/source/installation.html).

In the near future I will make more compatible this syntax.

Let me know if this solve the problem.

**Comment by ale94mleon** [comment] 2022-07-21 08:01
I will close this issue because the problem and the solutions are clear:
Problem:
The python version 3.8 is not compatible with the Type Hint `list[Chem.rdchem.Mol]`
Solutions
1. Install following the [instructions](https://moldrug.readthedocs.io/en/latest/source/installation.html#).
2. Update the python version.
3. Install the developer version of MolDrug directly from GitHub that already fixed the issue: `pip install git+https://github.com/ale94mleon/moldrug.git@main`

**Closed by ale94mleon** 2022-07-21 08:01 UTC
Labels: good first issue
